version: '3.8'

services:
  server:
    container_name: marvelog-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c 'while !</dev/tcp/mariadb/3306; do sleep 1; done; npm run start:localdebug'
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    env_file: .env.dev
    ports:
      - ${PORT}:${PORT}
      - 9239:9239
    networks:
      - webnet
    depends_on:
      - mariadb

  client:
    container_name: marvelog-client
    build:
      context: ../marvelog-client
      dockerfile: Dockerfile.dev
    volumes:
      - ../marvelog-client:/usr/app
      - /usr/app/node_modules
    env_file: .env.dev
    ports:
      - 4800:4800
    networks:
      - webnet
    depends_on:
      - server
    entrypoint: npm run start:docker

  mariadb:
    container_name: mariadb-dev
    image: mariadb:10.5.3-focal
    env_file: .env.dev
    networks:
      - webnet
    environment:
      TZ: 'America/Bahia'
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - ${OTS_PORT}:${DB_PORT}
    volumes:
      - dbdata:/var/lib/mysql

networks:
  webnet:
volumes:
  dbdata:
