FROM node:14.17-alpine3.10

WORKDIR /usr/app

COPY package*.json ./

RUN npm ci

COPY . .

RUN ENV=${ENV}

# Para debugar com banco remoto
# CMD ["npm", "run", "start:remotedebug"]

# Para debugar com um banco local docker
CMD ["npm", "run", "start:localdebug"]
